### ISSUE TITLE
Any possibility to use an object in url parameter??

### ISSUE THREAD

**Issue by alfecu** [Marcelh1983/document-viewer#10]
Id like to preview the document but I don’t have the url I have the blob document…how could I use your library?

thanks

**Comment by Marcelh1983** [comment]
Hi @alfecu, when using the google or office viewer it needs to be an public available document. There is no possibility to provide that viewer with a object url. The mammoth viewer and the default pdf viewer of the browser can.

**Comment by alfecu** [comment]
thanks a lot!
