### ISSUE TITLE
Suport for status output

### ISSUE THREAD

**Issue by biel-correa** [Marcelh1983/document-viewer#13]
It would be great to have this since some devs may want to use their own loading page instead of the in the package, also would be easier to catch errors

**Comment by Marcelh1983** [comment]
Hi @biel-correa, this package is just showing your document in an external viewer in an i-frame. The only thing this package can check is if the i-frame is loaded. This is an event that is dispatched. But if the iframe is loaded is doesn't mean your document is yet loaded in the viewer, but there is no way to get this information from outside the iframe
