### ISSUE TITLE
Memory Leaks on old Devices

### ISSUE THREAD

**Issue by SpraylnlPray** [Marcelh1983/document-viewer#14]
I'm using this component to show PDF reports in an app. Some of the devices using the app are very old and still use Firefox version 55. On these old devices the document-viewer causes increasing memory usage that eventually leads to a browser crash.

Is this a known issue with possibly a workaround? If not, could you maybe give me a hint on where to start investigating? Then I could maybe provide a general workaround.

**Comment by Marcelh1983** [comment]
Hi @SpraylnlPray. I guess its the external document viewer (google or office) that is causing this issue. If you are using google you can try office and vice versa.

**Comment by SpraylnlPray** [comment]
Hi @Marcelh1983, thank you for your quick answer.
I'm using `viewer="url"`, so I think there is neither google nor office involved, or I can't control which one is chosen. Do you have any other ideas?
