### ISSUE TITLE
Question: can we view an array of documents in this viewer?

### ISSUE THREAD

**Issue by sayedsadat344** [Marcelh1983/document-viewer#15]
This is not looking like an issue,  but for getting a quick answer I did prefer to ask here.

**Comment by RamonPortales** [comment]
how can shoud I configure to display any xls file ?

**Comment by Marcelh1983** [comment]
@sayedsadat344, in the same viewer that wouldn't be possible. 

Even multiple instances of ngx-doc-viewer using the google document viewer could result in strange behaviour because of the refresh logic that always checks for the first i-frame. I you would like to have multiple instances of ngx-doc-viewer using the google viewer I could look into the refresh issue.

**Comment by sayedsadat344** [comment]
@Marcelh1983 Thanks for the reply. Yep, as you said, I tried multiple ways to figure it out but, it was looking impossible.
I will change the doc with a click on the link, and it will render in the same viewer.

**Comment by sayedsadat344** [comment]
@Marcelh1983 Sorry to re-open the discussion, but there was a little issue I was facing working with ngx-doc-viewer, i.e. when I pass the link of the document from anywhere on the web it is rendered fine, but when I pass the document link from localhost, it is not working. It says no preview available. the following are examples of the links I am passing to the document URL.


the link which works (Online document)
`https://file-examples-com.github.io/uploads/2017/02/file-sample_100kB.doc`

the link from the local server (Not working)
`https://localhost:5001/Documents/CMSDocs/OrganizationDocuments/2021-06-24/c0cef432-5d70-47b6-ba05-25190821a6fb.docx`

Note: I tried bot viewers, google, and URL (google drive) viewers, but I could not render files from the local server.

**Comment by Marcelh1983** [comment]
@sayedsadat344 google drive an the google viewer cannot access your localhost. So there is no way to make this work from localhost.
