### ISSUE TITLE
How should I configure to display an xls office file

### ISSUE THREAD

**Issue by RamonPortales** [Marcelh1983/document-viewer#16]
@Marcelh1983 Help!!
I have trying to display some xls file and the only way that I have found is this

```
<ngx-doc-viewer *ngIf="show"
[url]= MyURL
viewer="google"
style="width:100%;height:50vh;">
```

the problem is that if my file is landscape or xls, the viewer just display the file as a portrait,
How should I configure the ngx-doc-viewer ?

**Real file**
![image](https://user-images.githubusercontent.com/45862198/123184560-8b595f00-d459-11eb-93a4-64be710fce72.png)

**How is displayed**
![image](https://user-images.githubusercontent.com/45862198/123184446-53eab280-d459-11eb-940a-2c7d3f08d101.png)

**Comment by Marcelh1983** [comment]
Hi @RamonPortales, I don't think this is possible. The only thing this package does is showing your document in the google document-viewer in an iframe. The only way to configure something like would be via the url e.g. a query-parameter to show the document in portrait mode, but a quick google didn't show this kind of options in the google documemt viewer.
