### ISSUE TITLE
ngx-doc-viewer not working with Angular12

### ISSUE THREAD

**Issue by zornic84** [Marcelh1983/document-viewer#17]
Good morning,

the current Version not working with Angular12

Best regards

**Comment by sayedsadat344** [comment]
Are there any errors?

I am using it with angular 11, so far no error.

**Comment by zornic84** [comment]
npm ERR! Found: @angular/common@12.1.0
npm ERR! node_modules/@angular/common
npm ERR!   @angular/common@"~12.1.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/common@"^11.2.0" from ngx-doc-viewer@2.0.2
npm ERR! node_modules/ngx-doc-viewer
npm ERR!   ngx-doc-viewer@"^2.0.2" from the root project

**Comment by zornic84** [comment]
Are you going to update this to Angular 12 in a timely manner? Otherwise I'll have to look for another tool and remove this...

**Comment by Marcelh1983** [comment]
Hi @zornic84 could you test 2.0.3?

**Comment by zornic84** [comment]
Hi @Marcelh1983 i've the same errors.. :-(

npm ERR! Could not resolve dependency:
npm ERR! peer @angular/common@"12.0.0" from ngx-doc-viewer@2.0.3
npm ERR! node_modules/ngx-doc-viewer
npm ERR!   ngx-doc-viewer@"^2.0.3" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

**Comment by Marcelh1983** [comment]
@zornic84 should be solved now in 2.0.4. Thanks for reporting and the patience.

**Comment by zornic84** [comment]
Hi @Marcelh1983 nice, yes, it works now. Thank you very much. Does the problem occur again when updating to version 13 or is this released for all versions?

**Comment by Marcelh1983** [comment]
@sayedsadat344 no I set the peerDependency on >= 10.0.0 so this issue won't occur in the future.
