### ISSUE TITLE
Why ngx-doc-viewer is not displaying pdf file(file is on local disk) in angular10?

### ISSUE THREAD

**Issue by fahadsubzwari924** [Marcelh1983/document-viewer#19]
In my `angular10` in which i have to display a `PDF` file as a preview. So for that i am using` ngx-doc-viewer.` My component is look like this

component.html

     <ngx-doc-viewer [url]="inputFile.filePath"
         viewer="google" style="width:100%;height:80vh">
     </ngx-doc-viewer>
my url is forming like this 
        `http://localhost:PORT/documents/bids/bidId704/proposalDoc_Monday_June_28th_2021_8_49_01_PM.pdf`

When i load just this url so that it loads `PDF` file in `chrome` perfectly but when i try with `ngx-doc-viewer` so it is giving an error one `chrome's console`

      `Unchecked runtime.lastError: Could not establish connection. Receiving end does not exist`.
      
How can i fix it?

**Comment by Marcelh1983** [comment]
Hi @fahadsubzwari924, the google viewer needs the file to be publicly available. So it probably will work when you deploy your application but the google viewer cannot access your localhost

**Comment by fahadsubzwari924** [comment]
So it will not work if i will change `viewer="url"` ?

**Comment by fahadsubzwari924** [comment]
> Hi @fahadsubzwari924, the google viewer needs the file to be publicly available. So it probably will work when you deploy your application but the google viewer cannot access your localhost

Now i am using `mammoth` for locally uploaded file preview but now it is previewing only `.docx` file. Other than `.docx` it is giving an error on console.  see this 
https://stackoverflow.com/questions/68166751/why-ngx-doc-viewer-is-not-displaying-pdf-filefile-is-on-local-disk-in-angular1/68167462#68167462

**Comment by wns-madhuri** [comment]
<ngx-doc-viewer [url]="inputFile.filePath"
     viewer="url">
 </ngx-doc-viewer>

How can i check content load or not. I m getting refuse to connect iframe.
