### ISSUE TITLE
I tried to use excel file show in popup using office. But not works IE11 browser. 

### ISSUE THREAD

**Issue by nagugondi31** [Marcelh1983/document-viewer#2]
I have implemented this in our apps. This excel file will render in the popup by browsing in chrome browser. Works fine here.
But the same one does not work for the IE11 browser. Refer to the attachment-related to this issue. Let me know.

<img width="960" alt="IE issue" src="https://user-images.githubusercontent.com/15884454/113297423-37d2eb80-9318-11eb-8e25-3dd6479edd1c.PNG">

Note I have followed the below URL for reference to implement.
1. https://stackblitz.com/edit/ngx-doc-viewer-example-8hychh
2. https://www.npmjs.com/package/ngx-doc-viewer

**Comment by nagugondi31** [comment]
@Marcelh1983 Can you give an update on this?

**Comment by Marcelh1983** [comment]
Hi @nagugondi31, Seems like Stackblitz itself doesn't open on IE11. I currently do not have the time to dive into the problem. You can debug the example application or copy-paste the component to your own application and try to see what goes wrong. If it's an issue in my code that can be fixed easily I'd like to know.

**Comment by nagugondi31** [comment]
Ok.
<iframe src="https://view.officeapps.live.com/op/embed.aspx?src=yourfile.xls" width="100%" height="500"></iframe>

Above one line of code works for me. For the query string "src" value should be URL of your file path.

**Comment by Marcelh1983** [comment]
Good to hear. This package is mainly just a wrapper for 3rd party viewers. For the Google viewer there is some logic to check if the document is loaded but that's not needed for the office viewer. So if you just use the office viewer I think adding the iframe with the office url is the best solution.

**Comment by rashmiRneha** [comment]
I am getting kinda same issue while previewing the .pptx,doc files. Can someone help?
