### ISSUE TITLE
not able to view .ppt, .pptx files using it

### ISSUE THREAD

**Issue by Tunisha-Mamsys** [Marcelh1983/document-viewer#23]
I am not able to view .ppt, .pptx files using it. Please help me with it.

**Comment by Marcelh1983** [comment]
Hi @Tunisha-Mamsys, could you be more specific? Do you use the google-viewer? Could you check the difference between my demo-application where ppt and pptx seems to work fine and your application?

**Comment by Tunisha-Mamsys** [comment]
Hi, Thanks for replying. I actually want to display .ppt and .pptx files in angular. I tried using office viewer and google viewer both but still it didn't work.
I used

<ngx-doc-viewer
  [url]="doc"
  viewer="google"
  style="width:100%;height:50vh;"
></ngx-doc-viewer>

this code only, in viewer I tried taking office and google.
in url, I gave the url of the document which is present on the server, but it didnt work.

Please help me for the same.

Thanks
Tunisha
________________________________

**Comment by Marcelh1983** [comment]
And the server is not running on localhost?

**Comment by Tunisha-Mamsys** [comment]
No, it is deployed on a server. If I open the same path in a browser, I am able to open the file, but not able to do the same with this.
________________________________

**Comment by Marcelh1983** [comment]
I upgraded my stackblitz example with the latest version. Could you check if it works if you paste in your document url [here](https://stackblitz.com/edit/ngx-doc-viewer-example?file=src%2Fapp%2Fapp.component.htm)?

**Comment by Tunisha-Mamsys** [comment]
No, it's not working.
________________________________

**Comment by Marcelh1983** [comment]
That's weird. Could you share the url of the document. Could be characters in the url, or there is something with the document itself

**Comment by Tunisha-Mamsys** [comment]
The document is accessible using VPN, can that cause any issue?
________________________________

**Comment by Marcelh1983** [comment]
That's the problem. Google's viewer gets your document and converts it to html. But Google won't be able to access your document so it would fail.
