### ISSUE TITLE
Add headers to request

### ISSUE THREAD

**Issue by JCarlos12** [Marcelh1983/document-viewer#3]
I am trying to load a document from our server.
But usually all requests needs to add a custom authorization header.

Is it possible to pass a header when loading the document based on the URL

**Comment by Marcelh1983** [comment]
Hi @JCarlos12. I assume you use the google of the office viewer. In that case the external viewer will get your document and you won't have a hook to add specific headers.

**Comment by JCarlos12** [comment]
Hi @Marcelh1983.  Im using the url viewer

`<ngx-doc-viewer
							[url]="testURL"
							viewer="url"
							style="width:100%;height:100%;"
						></ngx-doc-viewer>`
We have our own backend that holds all our files. Which when we need to request to them we always need to attach a authorization header to it or else it would return a 401.

We are using alfresco content services for the handling the files
https://api-explorer.alfresco.com/api-explorer/#/nodes/getNodeContent

They have a function that would return a files content but the response is in application/octet-stream

I was hoping if there is a prop for **ngx-doc-viewer** that could handle a octet-stream instead of a url. So that it could just render the data instead of the component requesting for the file data from the backend

**Comment by Marcelh1983** [comment]
the url viewer expects the url to point to a document viewer like: `https://docs.google.com/document/d/e/2PACX-1vRs3gemrszDinuGJCi_wO2m5XVP1q2SlRhxM8PAUYc3wu9LFsvteny7l6Rkp695-ruhfn3gWXV03yXC/pub?embedded=true` what document types do you want to show? I'm not sure this package can handle your requirements
