### ISSUE TITLE
Event

### ISSUE THREAD

**Issue by stas-lyu** [Marcelh1983/document-viewer#31]
Events not supported. Example: event onChange return current page, etc.

**Comment by Marcelh1983** [comment]
Hi @stas-lyu. Could you be more specific? You mean events on the document self? If you use one of the external viewers (office of google) then there is no way to get events because it's rendered on an external website and is displayed via this package in a iframe.

**Comment by stas-lyu** [comment]
I understand it. Sorry for terrible)
