### ISSUE TITLE
The same pdf file loads twice and shows one under another

### ISSUE THREAD

**Issue by Yura13** [Marcelh1983/document-viewer#32]
Sometimes I saw two loaded pdf files one under another (viewer="google"). It reproduces not often.

**Comment by Marcelh1983** [comment]
Hi @Yura13, thanks for reporting and sorry for the late reaction. I haven't been able to reproduce. Do you what other document is loaded under the other one? If it occurs inside the iframe it might be a bug in the google viewer.

**Comment by Yura13** [comment]
The same document loaded twice one under another. I saw the second document when scrolling through the first document. I reproduced it a couple of times but not constantly.
