### ISSUE TITLE
Angular Ivy distribution

### ISSUE THREAD

**Issue by hartmair** [Marcelh1983/document-viewer#34]
When compiling with Angular 13, the following pops up:
> $ ng serve
> ⠙ Generating browser application bundles (phase: setup)...Processing legacy "View Engine" libraries:
> - ngx-doc-viewer [es2015/esm2015] ()
> Encourage the library authors to publish an Ivy distribution.
> ✔ Browser application bundle generation complete.

**Comment by Marcelh1983** [comment]
It's fixed in version 2.1.0

**Comment by hartmair** [comment]
The warning is gone, however, I noticed a bundle size increase of about 27,76 KB
