### ISSUE TITLE
Can we get a version for react js

### ISSUE THREAD

**Issue by saiprasad9467** [Marcelh1983/document-viewer#35]

**Comment by Marcelh1983** [comment]
Hi @saiprasad9467, I created one a while ago: https://www.npmjs.com/package/react-documents

**Comment by saiprasad9467** [comment]
Ok thank you

**Comment by saiprasad9467** [comment]
There is no documentation for it
how should we use it
can you explain in detail

**Comment by saiprasad9467** [comment]
So i have implemented it but it is not full container wit
![Cropped](https://user-images.githubusercontent.com/63708628/147543649-b992a4f1-4bf8-45d6-9052-f250a2b63c04.png)
h

**Comment by saiprasad9467** [comment]
So the requirement is i need to have it (doc-view) in the full width for the Whole grid
