### ISSUE TITLE
Need to have full width for the preview

### ISSUE THREAD

**Issue by saiprasad9467** [Marcelh1983/document-viewer#36]
So the requirement is i need to have it (doc-view) in the full width for the Whole gri
![Cropped](https://user-images.githubusercontent.com/63708628/147576107-1118b2f9-e55e-474d-a85c-bbb04421de71.png)
d

**Comment by saiprasad9467** [comment]
Can we have it a full-width that will be displayed whole sub-part of the screen

**Comment by Marcelh1983** [comment]
I' not sure what you mean. But I assume you want to have influence on how the document self is rendered. Because it uses and external viewer I have no influence on how things are rendered inside the iframe. The iframe self can be created as wide as you want.
