### ISSUE TITLE
Reload content not working

### ISSUE THREAD

**Issue by diveshdobal** [Marcelh1983/document-viewer#4]
I tried to reload file but it does not work. Is it correct way to reload if content not loaded?

<ngx-doc-viewer url="sample.pdf" viewer="google"
  style="width:100%;height:350px;" [googleCheckContentLoaded]="true" googleCheckInterval="3000" googleMaxChecks="5">
</ngx-doc-viewer>

**Comment by Marcelh1983** [comment]
Looks good, even without passing contentLoaded properties it should work. You have document that something don't load and refreshing the page does show the document?

**Comment by diveshdobal** [comment]
Content is loading, but sometime it return 204 and does not load content. So I tried to reload it as described in readme. But it does not retry to load content. I am loading file from google cloud storage.

**Comment by Marcelh1983** [comment]
I just check the latest code to check the reload functionaltity. I works in the latest version. You should see a console message if it's reloading like: reloading..  main.e5425d459dc4ec2b404e.js:1, If you provide a stackblitz so I can reproduce I can check what's going on.
