### ISSUE TITLE
No options

### ISSUE THREAD

**Issue by gobi004** [Marcelh1983/document-viewer#41]
Hi,
There is no options like ng2-pdfjs-viewer such as go to page number by entering the page number and etc check the options section of ng2-pdfjs-viwer.
Blob formats which is from API  are not supporting like ng2-pdfjs-viewer it requires only direct URL which is not always supported in dynamic url paths So blob should be supportable
These kind of functionalities are will be helpful for users

**Comment by maniyahasu** [comment]
Hi @Marcelh1983,

Actually, I am trying to view .pdf and .docx files using this plugin with base64 encoded data but some how I unable to do so.
Could you please share Stackblitz example if you have any OR can you please assist me how I can render pdf/docx with base64 encoded data ?

I tried to explore doc url https://angular-doc-viewer.firebaseapp.com/ which is also not working propertly.

Appreciate your help :)

Thanks
