### ISSUE TITLE
Rotate issue in Edge Browser

### ISSUE THREAD

**Issue by Tulasireddy250** [Marcelh1983/document-viewer#43]
it is working in Chrome Browser but in the edge browser if rotate the first pdf, it will rotate all other pdf in current page. actually we have implement multiple pdf loading in same page side by side.

![image](https://user-images.githubusercontent.com/63843042/161213727-03556d25-1b9d-4c7d-aea2-ab50be4b5122.png)

**Comment by Marcelh1983** [comment]
HI @Tulasireddy250 I'm sorry for not responding, I was busy with other projects. I'm not sure this is something I could fix, because it's probably something the google viewer does.
