### ISSUE TITLE
"has no exported member" errors

### ISSUE THREAD

**Issue by kallyllacerda** [Marcelh1983/document-viewer#45]
I'm trying to run the application after installing the latest version of ngx-doc-viewer, but I'm getting several "has no exported member" errors, I tried to find some solutions on the internet, but nothing could fix it. How do I correct?

@angular/core version: 11.0.9

Following errors:

![erro-doc-viewer](https://user-images.githubusercontent.com/103464746/163203851-62c32654-1436-457c-8262-6f1bf102478a.PNG)

**Comment by Prefix1802** [comment]
Qout: "Following errors (i can't attach images here)"' :

You cant post images? I can....try editing your post.

**Comment by kallyllacerda** [comment]
I edited by inserting the image.

**Comment by kallyllacerda** [comment]
up

**Comment by Marcelh1983** [comment]
Think this is solved to matching the version number with the angular version
