### ISSUE TITLE
Problems in safari iOS

### ISSUE THREAD

**Issue by joseserrano15** [Marcelh1983/document-viewer#46]
I have a problem with the pdf view in safari, sometimes the pdf shows correctly but others only shows a white screen. Do you know what could be the problem?

correctly
![InkedIMG_6770_LI](https://user-images.githubusercontent.com/68348356/163264533-d6dae1fe-09ac-4168-b506-68367d563400.jpg)

problem
![InkedIMG_6771_LI](https://user-images.githubusercontent.com/68348356/163264558-8e7d63ce-f429-4c21-94e2-368a3baf84c3.jpg)

**Comment by elmartino** [comment]
Same problem here. Have you found a workaround / fix?

**Comment by Marcelh1983** [comment]
I don't know if this is a safari problem, the google viewer has some issues with first time rendering, thats why there are options to reload the page with a centain interval until this document is loaded succesfully. You can try to tweak the googleCheckInterval.
