### ISSUE TITLE
Breaks on Safari version 14.0.3

### ISSUE THREAD

**Issue by emmanuelmacharia** [Marcelh1983/document-viewer#5]
I've used the library in my angular application for a while now, but the update to Safari to version 14.0.3 seems to have broken something, as I can't view pdf documents anymore, and trying to load pdf documents up to display them, endlessly loads.
The file size is well below the limit, can't think of any other instance of why this is happening. 

Also, there arent any errors logged in the console

**Comment by Marcelh1983** [comment]
I'm sorry but I don't have any device here to test this issue. You could clone this repository and run the demo application to debug the problem. If you did and need further assistance, please let me know

**Comment by elmartino** [comment]
@emmanuelmacharia have you found a workaround?
