### ISSUE TITLE
Blob file is not loading to viewer

### ISSUE THREAD

**Issue by uvcreation** [Marcelh1983/document-viewer#51]
Below is the HTML snippet I'd used: 

`<ngx-doc-viewer
              [url]="doc"
              viewer="url"
              style="width:100%;height:50vh;">
            </ngx-doc-viewer>`

below is the component logic:

`const blob = new Blob([response], { type: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document' });
this.doc = URL.createObjectURL(blob);`

Error screenshot: 

![image](https://user-images.githubusercontent.com/11464816/189529861-372617fa-1804-4233-b64e-a88851da8fdd.png)

Is there something I am doing wrong? please do help.

**Comment by Marcelh1983** [comment]
HI @uvcreation what you try to do can work with the mammoth viewer not with viewer: url
