### ISSUE TITLE
Error in console

### ISSUE THREAD

**Issue by leocharrua** [Marcelh1983/document-viewer#52]
Hello. Thanks for your work ;)

I have this error in my project and exists in your demo too:

Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'report-sample' 'nonce-7hAmZwC6wdd7wq1Q9QLt7g' 'unsafe-inline' 'strict-dynamic' https: http: 'unsafe-eval'". Note that 'unsafe-inline' is ignored if either a hash or nonce value is present in the source list.

gview:9 Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'report-sample' 'nonce-7hAmZwC6wdd7wq1Q9QLt7g' 'unsafe-inline' 'strict-dynamic' https: http: 'unsafe-eval'". Note that 'unsafe-inline' is ignored if either a hash or nonce value is present in the source list.

{
    "result": {
        "error": {
            "code": -1,
            "message": "A network error occurred, and the request could not be completed."
        }
    },
    "body": "{\"error\":{\"code\":-1,\"message\":\"A network error occurred, and the request could not be completed.\"}}",
    "headers": {},
    "status": null,
    "statusText": null
}

For example, try with:  https://www.africau.edu/images/default/sample.pdf

**Comment by Marcelh1983** [comment]
Hi @leocharrua I'm going to clean up older issues so I'm closing it, I'm sorry for not responding I was too busy with other projects. I'm not sure what causes this I looks like some error from the google viewer. If you still having troubles here I'll can have a closer look if I have time. In that case I'll reopen the issue.

**Comment by leocharrua** [comment]
Hello @Marcelh1983, the issue still exists.

**Comment by GauravNagpure** [comment]
Hi @Marcelh1983 , I am also facing this issue.
