### ISSUE TITLE
Vunerabilities Error

### ISSUE THREAD

**Issue by tentaman** [Marcelh1983/document-viewer#53]
On a new install i get vulnerability issues.
npm audit fix does not correct it. 
 
Severity: high
loader-utils is vulnerable to Regular Expression Denial of Service (ReDoS) via url variable - https://github.com/advisories/GHSA-3rfm-jhwj-7488
loader-utils is vulnerable to Regular Expression Denial of Service (ReDoS) - https://github.com/advisories/GHSA-hhq3-ff78-jv3g

![image](https://user-images.githubusercontent.com/24694965/206570052-87c2c0e1-c79e-4324-bf5a-d7b9f03f509a.png)

**Comment by Marcelh1983** [comment]
Hi @tentaman I updated all dependencies in the latest version. Thanks for issue
