### ISSUE TITLE
Generic type 'ɵɵComponentDeclaration' requires between 7 and 8 type arguments.

### ISSUE THREAD

**Issue by waqqas-meraj-rt** [Marcelh1983/document-viewer#54]
With angular 14, on ng serve, I am getting this error:

`
Error: node_modules/ngx-doc-viewer/lib/document-viewer.component.d.ts:33:18 - error TS2707: Generic type ɵɵComponentDeclaration requires between 7 and 8 type arguments.
`
`
33 static ɵcmp: i0.ɵɵComponentDeclaration<NgxDocViewerComponent, "ngx-doc-viewer", never, { "url": "url"; "queryParams": "queryParams"; "viewerUrl": "viewerUrl"; "googleCheckInterval": "googleCheckInterval"; "googleMaxChecks": "googleMaxChecks"; "disableContent": "disableContent"; "googleCheckContentLoaded": "googleCheckContentLoaded"; "viewer": "viewer"; "overrideLocalhost": "overrideLocalhost"; }, { "loaded": "loaded"; }, never, never, false, never>;
`

It seems there is an extra parameter in ComponentDeclatation in document-viewer.d.ts in the end:
Changing to the following seems to fix the issue:
`    
static ɵcmp: i0.ɵɵComponentDeclaration<NgxDocViewerComponent, "ngx-doc-viewer", never, { "url": "url"; "queryParams": "queryParams"; "viewerUrl": "viewerUrl"; "googleCheckInterval": "googleCheckInterval"; "googleMaxChecks": "googleMaxChecks"; "disableContent": "disableContent"; "googleCheckContentLoaded": "googleCheckContentLoaded"; "viewer": "viewer"; "overrideLocalhost": "overrideLocalhost"; }, { "loaded": "loaded"; }, never, never, false>;
`

**Comment by rajibhalder** [comment]
@waqqas-meraj-rt @Marcelh1983 I am also getting same issue. In solution found ?

**Comment by Marcelh1983** [comment]
For Angular 14 you should use version 14 of this package

**Comment by rajibhalder** [comment]
@Marcelh1983 It worked after using version14. You can close this issue. No point keeping it open. Thanks.
