### ISSUE TITLE
.../ngx-doc-viewer could not be resolved to a NgModule class.

### ISSUE THREAD

**Issue by GlenTinashe** [Marcelh1983/document-viewer#6]
Hi. I get the following error after running ng build on my project running on Windows, Angular 11.2 and Node 15.12.

Error: node_modules/ngx-doc-viewer/ngx-doc-viewer/src/lib/document-viewer.module.d.ts:1:22 - error NG6002: Appears in the NgModule.imports of "Module", but could not be resolved to an NgModule class.

This likely means that the library (ngx-doc-viewer/ngx-doc-viewer/src/lib/document-viewer.module) which declares NgxDocViewerModule has not been processed correctly by ngcc, or is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see
if the library is expected to be compatible with Ivy.

How best can i resolve it?

**Comment by Marcelh1983** [comment]
Hi @GlenTinashe,

I just created a new application with the latest cli but I cannot reproduce the problem.
Could you create a repository that I can access to see if I can reproduce?

**Comment by sayedsadat344** [comment]
Any update regarding the issue?

**Comment by Marcelh1983** [comment]
HI @sayedsadat344  if you can provide me with a example so I can reproduce the problem I will have a look at the problem.
