### ISSUE TITLE
Can your script work on a regular vanilla javascript webpage using the script tag?

### ISSUE THREAD

**Issue by inglesuniversal** [Marcelh1983/document-viewer#7]
Also, I don't know what is the reason that both Google and Microsoft Document Viewers Rest API will NOT accept a link from a document stored on Firebase Storage (link below)

[FIREBASE_STORAGE_WORD_SAMPLE_DOCUMENT](https://firebasestorage.googleapis.com/v0/b/mycloudvip-storage.appspot.com/o/GMbRXZARq1AqDGD0xTZ4%2FnihZvJ4fwXQ2oO40ItWf.docx?alt=media&token=97628604-2ab4-4111-b531-085d545e1a93)

And incredibly your script handles that ulta-long URL perfectly!

**Comment by Marcelh1983** [comment]
HI @inglesuniversal , should work vanilla javascript if you use the code from: https://github.com/Marcelh1983/document-viewer/blob/main/libs/helper.ts
