### ISSUE TITLE
Error: Quotes are not supported for evaluation message on Angular App

### ISSUE THREAD

**Issue by hikhyper** [Marcelh1983/document-viewer#8]
Hello, 

Thanks for this helpful package. I tried the demo and it's actually the one that I'm looking for. 
So I installed today on a fresh angular app (version 8 and 11) it to my angular app, but unfortunately, I'm getting this error after following the setup from the docs.

![image](https://user-images.githubusercontent.com/80023612/118673373-863a3c00-b82b-11eb-9fa2-060a12d28f5a.png)

I only tried this snippet from the documentation:

```
<ngx-doc-viewer
  [url]="https://drive.google.com/file/d/0B5ImRpiNhCfGZDVhMGEyYmUtZTdmMy00YWEyLWEyMTQtN2E2YzM3MDg3MTZh/preview"
  viewer="url"
  style="width:100%;height:50vh;"
>
</ngx-doc-viewer>
```

I hope you can help me. This package is the one I really need. Thank you!

**Comment by joezak-outta** [comment]
Hello, I had the same error, I fixed it like this : 
change the url by adding single quote : 
old => "https://drive.google.com/file/d/0B5ImRpiNhCfGZDVhMGEyYmUtZTdmMy00YWEyLWEyMTQtN2E2YzM3MDg3MTZh/preview"
new one => "'https://drive.google.com/file/d/0B5ImRpiNhCfGZDVhMGEyYmUtZTdmMy00YWEyLWEyMTQtN2E2YzM3MDg3MTZh/preview'"

**Comment by hikhyper** [comment]
Thank you @joezak-outta !

**Comment by Marcelh1983** [comment]
Thanks @joezak-outta I will update the documentation.
